spring.application.name=book-revive-backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/bookrevive
spring.data.mongodb.database=bookrevive

# Server Port
server.port=8080

# Logging
logging.level.com.bookrevive=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

# Disable Spring Security default login page (we use our own auth)
spring.security.user.name=admin
spring.security.user.password=admin123

GEMINI_API_KEY=AIzaSyDSkisemYlqo11tCcYNusK-IeVkVBF-3dU
